### ISSUE TITLE
Redraw welcome screen illustrations

### ISSUE THREAD

**Issue by daudix-UFO** [GradienceTeam/Design#19]
For 0.8.0

**Comment by daudix-UFO** [comment]
Done in https://github.com/GradienceTeam/Design/commit/394c2d2f9f914fdf0346da6d31b75446d3eb67e9

**Comment by 0xMRTT** [comment]
https://github.com/GradienceTeam/Gradience/commit/e74ef23c5824eea04c85df40520990b2f6efe79c for the code
